version: '3.7'
services:
  pg_db:
    image: postgres
#    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    ports:
      - '5432:5432'

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'

